project:
  type: website
  resources:
    - objects.json

metadata-files:
  - reference/_sidebar.yml

website:
  title: Shiny
  navbar:
    left:
      - file: reference/index.qmd
        text: "Reference"
    right:
      - icon: github
        href: https://github.com/rstudio/py-shiny

format:
  html:
    theme:
      light: cosmo
    toc: true

filters:
  - interlinks
  - shinylive

interlinks:
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/

quartodoc:
  style: pkgdown
  dir: reference
  package: shiny
  out_index: _api_index.qmd
  display_name: relative
  sidebar: reference/_sidebar.yml
  renderer:
    style: _renderer.py
    show_signature_annotations: false
    display_name: relative
  sections:
    - title: Page containers
      desc: Create a user interface page container.
      contents:
        - ui.page_navbar
        - ui.page_fluid
        - ui.page_fixed
        - ui.page_bootstrap
    - title: UI Layout
      desc: Control the layout of multiple UI components.
      contents:
        - ui.layout_sidebar
        - ui.panel_sidebar
        - ui.panel_main
        - ui.column
        - ui.row
    - title: UI Inputs
      desc: Create UI that prompts the user for input values or interaction.
      contents:
        - ui.input_select
        - ui.input_selectize
        - ui.input_slider
        - ui.input_date
        - ui.input_date_range
        - ui.input_checkbox
        - ui.input_checkbox_group
        - ui.input_switch
        - ui.input_radio_buttons
        - ui.input_numeric
        - ui.input_text
        - ui.input_text_area
        - ui.input_password
        - ui.input_action_button
        - ui.input_action_link
    - title: Update inputs
      desc: Programmatically update input values.
      contents:
        - ui.update_select
        - ui.update_selectize
        - ui.update_slider
        - ui.update_date
        - ui.update_date_range
        - ui.update_checkbox
        - ui.update_checkbox_group
        - ui.update_switch
        - ui.update_radio_buttons
        - ui.update_numeric
        - ui.update_text
        # TODO: griffe loads this as an Attribute, but it is simply the above
        # function assigned to a new variable.
        #- ui.update_text_area
        - ui.update_navs
    - title: Navigation (tab) panels
      desc: Create segments of UI content.
      contents:
        - ui.nav
        - ui.nav_control
        - ui.nav_spacer
        - ui.nav_menu
        - ui.navset_tab
        - ui.navset_tab_card
        - ui.navset_pill
        - ui.navset_pill_card
        - ui.navset_pill_list
    - title: UI panels
      desc: Visually group together a section of UI components.
      contents:
        - ui.panel_absolute
        - ui.panel_fixed
        - ui.panel_conditional
        - ui.panel_title
        - ui.panel_well
    - title: Uploads & downloads
      desc: Allow users to upload and download files.
      contents:
        - ui.input_file
        - ui.download_button
    - title: Custom UI
      desc: Lower-level UI functions for creating custom HTML/CSS/JS
      contents:
        # TODO: the module overshadows the class. see griffe issue
        - ui.HTML       # uses justattributes.rst template
        - ui.TagList    # uses class.rst template
        # TODO: this is a module that produces another index
        # - ui.tags       # uses tags.rst template
        - ui.markdown
        - ui.insert_ui
        - ui.remove_ui
    - title: Rendering outputs
      desc: "UI (output_*()) and server (render)ing functions for generating content server-side."
      contents:
        - ui.output_plot
        - render.plot
        - ui.output_image
        - render.image
        - ui.output_table
        - render.table
        - ui.output_text
        - ui.output_text_verbatim
        - render.text
        - ui.output_ui
        - render.ui
    - title: Reactive programming
      desc: ""
      contents:
        # toc 1
        - reactive.Calc
        - reactive.Effect

        # toc 2
        - reactive.Value

        # toc 3
        - reactive.isolate
        - reactive.invalidate_later
        - reactive.flush
        - reactive.poll
        - reactive.file_reader
        # TODO: fails to load
        # - event
    - title: Create and run applications
      desc: ""
      contents:
        - run_app

        # uses class.rst template
        - App
        - Inputs
        - Outputs
        - Session
    - title: Display messages
      desc: ""
      contents:
        - ui.help_text
        - ui.notification_show
        - ui.notification_remove
        - ui.modal
        - ui.modal_show
        - ui.modal_remove
        - ui.modal_button
        - ui.Progress          # uses class.rst
    - title: Error validation
      desc: ""
      contents:
        # uses class.rst template
        - types.SilentException
        - types.SilentCancelOutputException
        - types.SafeException
    - title: Modules
      desc: ""
      contents:
        # uses class.rst template
        - module.ui
        - module.server
    - title: Type hints
      desc: ""
      contents:
        # uses justattributes.rst template
        - types.FileInfo
        - types.ImgData
    - title: Developer facing tools
      desc: ""
      contents:
        - session.get_current_session
        - session.require_active_session
        - session.session_context
        - reactive.get_current_context
        # TODO: this is loaded as an attribute, since it's an instance of a
        # custom class
        #- input_handler.input_handlers
